---
name: Test Debugger Action
on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  oidc_debug_test:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    name: A test of the oidc debugger
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Debug OIDC Claims
        uses: ./
        with:
          # revert?
          audience: "${{ github.server_url }}/${{ github.repository_owner }}"
